/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.rogerio.app;

import br.com.rogerio.bll.ApartamentoBll;
import br.com.rogerio.bll.CalcularComissaoAutonomo;
import br.com.rogerio.bll.CalcularComissaoCLT;
import br.com.rogerio.model.Apartamento;
import javax.swing.JOptionPane;

/**
 *
 * @author roger
 */
public class CalcularComissaoView extends javax.swing.JFrame {

    Apartamento apto;
    ApartamentoBll bllAutonomo;
    ApartamentoBll bllCLT;

    /**
     * Creates new form CalcularComissaoView
     */
    public CalcularComissaoView() {
        initComponents();

        apto = new Apartamento();
        bllAutonomo = new CalcularComissaoAutonomo();
        bllCLT = new CalcularComissaoCLT();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelComissaoDeVendedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxAltoPadrao = new javax.swing.JCheckBox();
        jCheckBoxMedio = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxAutonomo = new javax.swing.JCheckBox();
        jCheckBoxCLT = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldValorApto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSaidaDadosApartamento = new javax.swing.JTextArea();
        jButtonCalcularComissao = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTamanho = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcular Comissão de Vendedor");
        setResizable(false);

        jLabel1.setText("Tipo do Padrão do Apartamento:");

        jCheckBoxAltoPadrao.setText("Alto Padrão");
        jCheckBoxAltoPadrao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxAltoPadraoMouseClicked(evt);
            }
        });

        jCheckBoxMedio.setText("Médio Padrão");
        jCheckBoxMedio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxMedioMouseClicked(evt);
            }
        });

        jLabel2.setText("Categoria do Vendedor:");

        jCheckBoxAutonomo.setText("Autônomo");
        jCheckBoxAutonomo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxAutonomoMouseClicked(evt);
            }
        });

        jCheckBoxCLT.setText("CLT");
        jCheckBoxCLT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxCLTMouseClicked(evt);
            }
        });

        jLabel3.setText("Valor do Apartamento R$:");

        jTextFieldValorApto.setText("1000");

        jTextAreaSaidaDadosApartamento.setColumns(20);
        jTextAreaSaidaDadosApartamento.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSaidaDadosApartamento);

        jButtonCalcularComissao.setText("Calcular Comissão");
        jButtonCalcularComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularComissaoActionPerformed(evt);
            }
        });

        jLabel4.setText("Tamanho: ");

        jTextFieldTamanho.setText("250");

        jLabel5.setText("mts2");

        javax.swing.GroupLayout jPanelComissaoDeVendedorLayout = new javax.swing.GroupLayout(jPanelComissaoDeVendedor);
        jPanelComissaoDeVendedor.setLayout(jPanelComissaoDeVendedorLayout);
        jPanelComissaoDeVendedorLayout.setHorizontalGroup(
            jPanelComissaoDeVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComissaoDeVendedorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelComissaoDeVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComissaoDeVendedorLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelComissaoDeVendedorLayout.createSequentialGroup()
                        .addGroup(jPanelComissaoDeVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelComissaoDeVendedorLayout.createSequentialGroup()
                                .addGroup(jPanelComissaoDeVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelComissaoDeVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelComissaoDeVendedorLayout.createSequentialGroup()
                                        .addGroup(jPanelComissaoDeVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBoxAltoPadrao)
                                            .addComponent(jCheckBoxAutonomo))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelComissaoDeVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBoxMedio)
                                            .addComponent(jCheckBoxCLT)))
                                    .addGroup(jPanelComissaoDeVendedorLayout.createSequentialGroup()
                                        .addComponent(jTextFieldValorApto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonCalcularComissao)))))
                        .addContainerGap(25, Short.MAX_VALUE))))
        );
        jPanelComissaoDeVendedorLayout.setVerticalGroup(
            jPanelComissaoDeVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComissaoDeVendedorLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelComissaoDeVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCheckBoxAltoPadrao)
                    .addComponent(jCheckBoxMedio))
                .addGap(36, 36, 36)
                .addGroup(jPanelComissaoDeVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCheckBoxAutonomo)
                    .addComponent(jCheckBoxCLT))
                .addGap(18, 18, 18)
                .addGroup(jPanelComissaoDeVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addGroup(jPanelComissaoDeVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldValorApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCalcularComissao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelComissaoDeVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelComissaoDeVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularComissaoActionPerformed

        try {

            if (jCheckBoxAltoPadrao.isSelected()) {
                apto.setPadrao("Alto Padrão");
            } else if (jCheckBoxMedio.isSelected()){
                apto.setPadrao("Médio Padrão");
            }
            
            apto.setTamanho(Integer.parseInt(jTextFieldTamanho.getText()));
            apto.setValor(Double.parseDouble(jTextFieldValorApto.getText()));
            

            if (jButtonCalcularComissao.getLabel().equalsIgnoreCase("Autônomo")) {
                String categoriaVendedor = "Autônomo";
                
                bllAutonomo.pagarComissao(apto, categoriaVendedor);
                jTextAreaSaidaDadosApartamento.setText(apto.toString() + bllAutonomo.toString());

            } else {

                String categoriaVendedor = "CLT";
                bllCLT.pagarComissao(apto, categoriaVendedor);
                jTextAreaSaidaDadosApartamento.setText(apto.toString() + bllCLT.toString());
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Atenção !!!\n" + erro.getMessage());
        }


    }//GEN-LAST:event_jButtonCalcularComissaoActionPerformed

    private void jCheckBoxAltoPadraoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxAltoPadraoMouseClicked
        
            jCheckBoxMedio.setSelected(false);

    }//GEN-LAST:event_jCheckBoxAltoPadraoMouseClicked

    private void jCheckBoxAutonomoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxAutonomoMouseClicked
        jCheckBoxCLT.setSelected(false);
        jButtonCalcularComissao.setLabel("Autônomo");
    }//GEN-LAST:event_jCheckBoxAutonomoMouseClicked

    private void jCheckBoxCLTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxCLTMouseClicked
        jCheckBoxAutonomo.setSelected(false);
        jButtonCalcularComissao.setLabel("CLT");
        
    }//GEN-LAST:event_jCheckBoxCLTMouseClicked

    private void jCheckBoxMedioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxMedioMouseClicked
        jCheckBoxAltoPadrao.setSelected(false);
    }//GEN-LAST:event_jCheckBoxMedioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcularComissaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcularComissaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcularComissaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcularComissaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcularComissaoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcularComissao;
    private javax.swing.JCheckBox jCheckBoxAltoPadrao;
    private javax.swing.JCheckBox jCheckBoxAutonomo;
    private javax.swing.JCheckBox jCheckBoxCLT;
    private javax.swing.JCheckBox jCheckBoxMedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelComissaoDeVendedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSaidaDadosApartamento;
    private javax.swing.JTextField jTextFieldTamanho;
    private javax.swing.JTextField jTextFieldValorApto;
    // End of variables declaration//GEN-END:variables
}
